---
- name: Set up RHOSO/RHELAI passthrough
  hosts: "{{ override_hosts | default('all', true) }}"
  strategy: linear
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  tasks:
    - ansible.builtin.import_role:
        name: setup_gpu
        tasks_from: install.yml
    - ansible.builtin.import_role:
        name: setup_gpu
        tasks_from: iommu.yml
    - ansible.builtin.import_role:
        name: setup_gpu
        tasks_from: gpuinfo.yml
    - ansible.builtin.import_role:
        name: setup_gpu
        tasks_from: drivers.yml
    - ansible.builtin.import_role:
        name: setup_gpu
        tasks_from: vfio.yml
    - ansible.builtin.import_role:
        name: setup_gpu
        tasks_from: grub.yml
